export const MODALS = {
  CREATE_ITEM_MODAL: 'CREATE_ITEM_MODAL',
  CREATE_CATEGORY_MODAL: 'CREATE_CATEGORY_MODAL',
  EDIT_ITEM_MODAL: 'EDIT_ITEM_MODAL',
  EDIT_CATEGORY_MODAL: 'EDIT_CATEGORY_MODAL',
  DELETE_ITEM_MODAL: 'DELETE_ITEM_MODAL',
  DELETE_CATEGORY_MODAL: 'DELETE_CATEGORY_MODAL',
};
